### ISSUE TITLE
Close audio output when no audio is being generated

### ISSUE THREAD

**Issue by wattelengineering** [gamingdoom/datcord#23]
This may have been addressed by #16 but will still need to be released once upstream becomes available.

There is a bug in Firefox that prevents audio streams from being closed even when no sound is being generated. See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1743834

This causes an annoying fault where bluetooth multipoint fails. See (it affects more headsets than just the Sony one):

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2097

As a result, when datcord is running, phones that are paired to the same headset as the PC cannot produce any sound. I've tested this and simply closing datcord allows playback from the phone. Once datcord is back up and running and the phone audio stops, the PC will take over the audio and never let it go preventing the any subsequent output from the phone until datcord is closed.

If I'm reading #16 correctly, not much needs to be done, just rebuild/re-release as soon as Firefox 102 becomes available. However, there may also be something in the way discord/datcord functions that keeps the audio sink open forever while the app is running.

**Comment by gamingdoom** [comment]
Hello,
The latest build from GitHub Actions should be built with at least Firefox 102.0 beta. Could you check if it works?

[Appimage](https://github.com/gamingdoom/datcord/suites/6790614289/artifacts/260368842)
[Tarball](https://github.com/gamingdoom/datcord/suites/6790614289/artifacts/260368843)

**Comment by akengconsulting** [comment]
Just checked it using the link you provided to the Appimage and the symptoms are exactly the same. Phone works when datcord is off. When datcord is launched, the phone continues to play until stopped. Then the phone can never play again until datcord has been quit. I'm not sure if the patch linked above has been properly applied though since the the phone doesn't even regain the ability to play sound over BT with datcord (and speech-distpatcher-dummy) muted in the audio settings. I think the patch was meant to specifically address that.

Looks also like discord just keeps the audio sink running forever (the speaker icon is visible in the datcord icon in the taskbar). Do you have any control over that?

**Comment by gamingdoom** [comment]
Hello,
I have rebuilt Datcord with the newest changes from Mozilla. I have not done anything special to Datcord that would cause this behavior. Everything that happens when you open [discord](https://discord.com/app) in Firefox should happen with Datcord. I do not have any control over it besides from applying the aforementioned patch to the source code (it seems that Mozilla has already done that).

[Appimage](https://github.com/gamingdoom/datcord/suites/6868768459/artifacts/265716352)
[Tarball](https://github.com/gamingdoom/datcord/suites/6868768459/artifacts/265716354)

**Comment by akengconsulting** [comment]
So to add a little extra, I just downloaded both Firefox beta (102.0b8) and nightly (103.0a1) and the symptoms are the same. So I'm not sure if the patch has been merged on their end yet. It has been submitted and accepted but may not be in the main line yet.

So maybe revisit when 102 gets officially released? I don't know.

**Comment by gamingdoom** [comment]
Hello,
It has been a couple of months and I think it is time to revisit this issue and test the newest version of Datcord and/or Firefox.

[Appimage](https://github.com/gamingdoom/datcord/suites/8161212964/artifacts/354429981)
[Tarball](https://github.com/gamingdoom/datcord/suites/8161212964/artifacts/354429982)

**Comment by akengconsulting** [comment]
Hi,

Just tested your Datcord appimage and the latest Firefox (104.0.2) and the symptoms are exactly the same. Youtube and Twitch (as examples) work as I expect - even pausing allows the phone to produce audio. Discord blocks audio - even when "deafen" is activated. The only way to allow the phone to produce audio is to quit the Discord app (close Datcord or log out/close tab), or change the output device to be something other than the BT device. Chrome browsers work as I'd expect (deafen/mute tab closes the audio stream).

So either I didn't understand what the Firefox patch was fixing, or there's some corner case where the AudioCallbackDriver functions differently to the AudioStream.

**Comment by gamingdoom** [comment]
Hello,
Does this still happen in Firefox 120? Datcord is now using that.

**Comment by wattelengineering** [comment]
So I think this may be solved. I'm not 100% sure. I just tested it using both the appimage and the flatpak (and firefox too) and I can get it to work with a little poking. Basically, I can get datcord to make a noise and stop, then I need to press the play/pause button on my headset and then it will finally work. I tried with another headset and it doesn't have that problem.

More detail:
Previously, chrome and firefox based browsers (including datcord) would act differently. Firefox based ones would keep an audio stream running indefinitely whereas chrome ones would turn it off eventually. Firefox ones STILL do this, but the functionality is not the same between the two (audio won't work until I press the play/pause button on the headset). That is, both chrome and firefox fail to play until I press the button. Previously, chrome browsers would start playing without interference after a few seconds. So I think me headset has developed a new problem sometime in the last year or so (firmware update or whatever), that has caused an additional problem, but that has nothing to do with datcord. If no one else reports such an issue, I think this issue can be solved.
